weights: /content/drive/MyDrive/PBL5/Yolov7/yolov7/runs/train/yolov7tiny_tfs_newDS3/weights/last.pt
cfg: ''
data: /content/PBL5-1/data.yaml
hyp: data/hyp.scratch.tiny.yaml
epochs: 50
batch_size: 16
img_size:
- 640
- 640
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: yolov7tiny_tfs_newDS
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
world_size: 1
global_rank: -1
save_dir: runs/train/yolov7tiny_tfs_newDS3
total_batch_size: 16
